apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-database
spec:
  selector:
    matchLabels:
      app: prod-db
  template:
    metadata:
      labels:
        app: prod-db
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
        - image: postgres:latest
          name: prod-db
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: DB_NAME
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          ports:
            - containerPort: 5432
              name: prod-db-port
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data