
- name: Install Docker SDK for Python
  pip:
    name:
      - "docker<5"
  become: yes

- name: Create docker network
  docker_network:
    name: app-network-dev

- name: Create dev directory
  file:
    path: /tmp/dev
    state: directory
    mode: 0777
    recurse: yes

- name: Clone repo with source code
  git:
    repo: https://github.com/star1can/sberops_f2022.git
    dest: /tmp/dev/repo
    version: hw1
    force: true

- name: Copy properties
  copy:
    src: application.properties
    dest: /tmp/dev/repo/simpleApp/greeting-service/

- name: Copy script
  copy:
    src: build_and_run.sh
    dest: /tmp/dev/repo/simpleApp/greeting-service/

- name: Create db container for dev
  docker_container:
    image: postgres
    name: dev-db
    state: started
    ports: "5434:5432"
    env:
        POSTGRES_USER: "{{USER}}"
        POSTGRES_PASSWORD: "{{PASSWORD}}"
        POSTGRES_DB: "{{DB_NAME}}"
        POSTGRES_HOST: "{{HOST}}"
        POSTGRES_PORT: "{{PORT}}"
    networks:
      - name: app-network-dev
    volumes:
      - /tmp/ansible-project/dev/dev-db/data:/var/lib/postgresql/data
    restart_policy: on-failure

- name: Create adminer for db
  docker_container:
    image: adminer
    name: adminer
    state: started
    ports: "8083:8080"
    networks:
      - name: app-network-dev
    restart_policy: on-failure

- name: Create backend container for dev
  docker_container:
    image: openjdk:17-oracle
    name: greeting-service-dev
    state: started
    ports: "8081:8080"
    command: /app/build_and_run.sh
    volumes:
      - /tmp/ansible-project/dev/repo/simpleApp/greeting-service:/app
    networks:
      - name: app-network-dev
    restart_policy: always
