version: '3.7'

services:
  jenkins:
    build: ./
    image: jenkins-with-dc
    container_name: jenkins
    ports:
      - 8002:8080
      - 50000:50000
    networks:
      static-network:
        ipv4_address: 172.20.127.1
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  sonarqube:
    image: sonarqube:community
    depends_on:
      - sonar-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    networks:
      static-network:
        ipv4_address: 172.20.127.2
    volumes:
      - ./sonar/sonarqube_data:/opt/sonarqube/data
      - ./sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonar/sonarqube_logs:/opt/sonarqube/logs
  
  sonar-db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    ports:
      - "5435:5432"
    networks:
      static-network:
        ipv4_address: 172.20.127.3
    volumes:
      - ./sonar/sonar-db/postgresql:/var/lib/postgresql
      - ./sonar/sonar-db/data:/var/lib/postgresql/data

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16