apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: backend-pod
      labels:
        app: greeting-service
    spec:
      containers:
      - image: tuzzik/greeting-service
        name: greeting-service-container
        command:
          - java -jar /app/greeting-service-0.0.1-SNAPSHOT.jar --spring.config.location=/app/config/application.properties
        ports:
        - containerPort: 8080
          name: back-port
        volumeMounts:
        - name: config
          mountPath: /app/config/
          readOnly: true
        imagePullPolicy: IfNotPresent

      volumes:
      - name: config
        configMap:
          name: back-cm
          items:
          - key: application.properties
            path: application.properties