apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: backend-pod
      labels:
        app: greeting-service
    spec:
      containers:
      - image: tuzzik/greeting-service
        name: greeting-service-container
        ports:
        - containerPort: 8080
          name: back-port
        volumeMounts:
        - name: config
          mountPath: /app/application.properties
          subPath: application.properties
          readOnly: true
        imagePullPolicy: IfNotPresent

      volumes:
      - name: config
        configMap:
          name: back-cm
          items:
          - key: application.properties
            path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: greeting-service