version: '3.7'
services:

  app:
    image: starican/greeting-service:latest
    container_name: greeting-service
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - '8080:8080'
    restart: on-failure

  db:
    image: postgres:latest
    container_name: db-service
    networks:
      - app-network
    ports:
      - '5433:5432'
    env_file:
      - ./db/database.env
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: on-failure

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - '8180:8080'
    restart: on-failure

networks:
      app-network:
          driver: bridge